### ISSUE TITLE
How can I check and give consent?

### ISSUE THREAD

**Issue by plompd** [ddm-studio/cookie-byte#1]
I try to use this syntax, but it won't work. How does this work?

`{{ cookie_consent has="marketing-cookies" }}
    {{ partial:fathom }}
{{ /cookie_consent has="marketing-cookies" }}`

Or can I use an IF statement? How can I render a partial if consent has been given?

**Comment by ddm-studio** [comment]
Hi, this must be wrapped in an IF-Statement:

`{{ if !{ cookie_consent has="marketing" } }}
...
{{ /if }}`

Can you please try that and let us know?
Thanks for the hint though, we will add this to the documentation.

**Comment by plompd** [comment]
Thanks. I indeed saw this being used in another addon, and it worked.
