### ISSUE TITLE
Composer Update overwrites modified css and js files

### ISSUE THREAD

**Issue by Ceepster14** [ddm-studio/cookie-byte#4]
When running a composer update, the base css and js files get republished to the \public\vendor directory which overwrites any customisations! Example below:

        > Statamic\Console\Composer\Scripts::preUpdateCmd
        Loading composer repositories with package information
        Updating dependencies
        Lock file operations: 0 installs, 2 updates, 0 removals
          - Upgrading nunomaduro/collision (v5.7.0 => v5.8.0)
          - Upgrading statamic/cms (v3.1.32 => v3.1.33)
        Writing lock file
        Installing dependencies from lock file (including require-dev)
        Package operations: 0 installs, 2 updates, 0 removals
          - Downloading statamic/cms (v3.1.33)
          - Downloading nunomaduro/collision (v5.8.0)
          - Upgrading statamic/cms (v3.1.32 => v3.1.33): Extracting archive
          - Upgrading nunomaduro/collision (v5.7.0 => v5.8.0): Extracting archive
          - Downloading statamic/cms (dist)
          - Installing statamic/cms (dist): Extracting archive
        Generating optimized autoload files
        > Illuminate\Foundation\ComposerScripts::postAutoloadDump
        > @php artisan package:discover --ansi
        Discovered Package: aerni/social-links
        Discovered Package: barryvdh/laravel-debugbar
        Discovered Package: ddm-studio/cookie-byte
        Discovered Package: facade/ignition
        Discovered Package: fideloper/proxy
        Discovered Package: fruitcake/laravel-cors
        Discovered Package: intervention/image
        Discovered Package: laravel/tinker
        Discovered Package: nesbot/carbon
        Discovered Package: nunomaduro/collision
        Discovered Package: rebing/graphql-laravel
        Discovered Package: spatie/laravel-ray
        Discovered Package: spatie/statamic-responsive-images
        Discovered Package: statamic/cms
        Discovered Package: wilderborn/partyline
        Discovered Package: withcandour/aardvark-seo
        Package manifest generated successfully.
        > @php artisan statamic:install --ansi
        Discovered Addon: aerni/social-links
        Discovered Addon: ddm-studio/cookie-byte
        Discovered Addon: spatie/statamic-responsive-images
        Discovered Addon: withcandour/aardvark-seo
        Addon manifest generated successfully.
        Copied Directory [\vendor\statamic\cms\resources\users] To [\resources\users]
        Publishing complete.
        Copied Directory [\vendor\statamic\cms\resources\dist] To [\public\vendor\statamic\cp]
        Publishing complete.
        Publishing complete.
        Copied Directory [\vendor\ddm-studio\cookie-byte\dist\css] To [\public\vendor\cookie-byte\css]
        Copied Directory [\vendor\ddm-studio\cookie-byte\dist\js] To [\public\vendor\cookie-byte\js]
        Publishing complete.
        Copied File [\vendor\spatie\statamic-responsive-images\dist\css\responsive.css] To [\public\vendor\statamic-responsive-images\css\responsive.css]
        Copied File [\vendor\spatie\statamic-responsive-images\dist\js\responsive.js] To [\public\vendor\statamic-responsive-images\js\responsive.js]
        Publishing complete.
        Copied File [\vendor\withcandour\aardvark-seo\public\css\aardvark-seo.css] To [\public\vendor\aardvark-seo\css\aardvark-seo.css]
        Copied File [\vendor\withcandour\aardvark-seo\public\js\aardvark-seo.js] To [\public\vendor\aardvark-seo\js\aardvark-seo.js]
        Publishing complete.
        Compiled views cleared!
        Application cache cleared!
        105 packages you are using are looking for funding.
        Use the `composer fund` command to find out more!

**Comment by Ceepster14** [comment]
Forgot to mention that toggling the Custom CSS Styling button in the control panel doesn't appear to affect this

**Comment by ddm-dano** [comment]
Sorry for the late reply, I unfortunately did not have my notification turned on.

As far as I can see the CSS and JavaScript files in the public/ folder are automatically overwritten. This is a desired behavior, because these are the files that are included when you don't have Custom CSS/JS enabled.

If you want to customize these stylings or scripts you should export them before with ``php artisan vendor:publish`` and the tag ``cookie-byte-resources-custom`` to the resource paths and edit them there. The idea is so you can include them in your site's css instead of adding our files.

If you have any further questions or I misunderstood the problem feel free to write me again. If this solved your problem please close this issue.

**Comment by Ceepster14** [comment]
Hi,

No worries! It just caught me unawares - I'll modify accordingly.

Thanks
