### ISSUE TITLE
Asset container for bg_image is not configurable

### ISSUE THREAD

**Issue by K3CK** [ddm-studio/cookie-byte#5]
The asset container for the bg_image setting is hard coded in Configuration/ConfigBlueprint.php. If there is no container with the handle "asset" then the Settings page in the Control Panel is not accessible. An exception is raised:
`Statamic\Fieldtypes\Assets\UndefinedContainerException - An asset container has not been configured`

Is there a way to overwrite the default assets container?

**Comment by dryven-dano** [comment]
Thank you for noticing! I added an option in the config file, so you can configure the asset container in which the background image is located! You just have to do the following:

```sh
php artisan vendor:publish --tag=cookie-byte-config
```

**config/cookie-byte.php**
```
'asset_container' => '<your-asset-handle-here>'
```
